#!/usr/bin/env node

'use strict'

let fs = require('fs')
let fm = require('front-matter')
let argv = require('minimist')(process.argv.slice(2))

let md_parse = function(file, idx) {
    return new Promise( (resolve, reject) => {
	fs.readFile(file, 'utf8', (err, data) => {
	    if (err) {
		reject(err)
		return
	    }
	    let r = fm(data)
	    resolve({
		idx: idx,
		subject: r.attributes.subject || '(No Subject)',
		authors: [].concat(r.attributes.authors || 'Anonymous')
	    })
	})
    })
}


if (!argv._.length) {
    console.error("Usage: index YYYY/DD/MM/1.md ...")
    process.exit(1)
}

let index = {
    "posts": [],
    "authors": []
}
let parsed = []
let files = argv._.sort()

files.forEach( (file, idx) => {
    let m = file.match(/(\d{4})\/(\d{2})\/(\d{2})\/(.+).md$/)
    if (!m) {
	if (argv.v) console.error(`ignoring ${file}`)
	return
    }

    let promise = md_parse(file, idx)
	.then( (meta) => {
	    meta.authors.forEach( (ar) => {
		if (-1 === index.authors.indexOf(ar))
		    index.authors.push(ar)
	    })

	    index.posts[meta.idx] = {
		n: m[4],
		y: m[1],
		m: m[2],
		d: m[3],
		s: meta.subject,
		a: meta.authors.map( (name) => {
		    return index.authors.indexOf(name)
		})
	    }
	})
	.catch((err) => {
	    console.error(err.message)
	    process.exit(1)
	})

    parsed.push(promise)
})

Promise.all(parsed).then( ()=> {
    process.stdout.write(JSON.stringify(index))
})
